FROM gradle:8.2-jdk17 AS build
COPY . /work
WORKDIR /work
RUN gradle distZip -Dorg.gradle.daemon=false

FROM openjdk:17-jdk-alpine
WORKDIR /app
RUN apk add unzip
COPY --from=build /work/build/distributions/FoodPollBot-*.zip ./FoodPollBot.zip
RUN unzip FoodPollBot.zip && mv FoodPollBot-*/* . && rm -r FoodPollBot*
ENTRYPOINT ["/app/bin/FoodPollBot"]
