FROM openjdk:17-jdk-slim
WORKDIR /app
COPY --from="ghcr.io/luca-heitmann/foodpollbot:1.0.0-amd64" /app/*.jar ./app.jar
ENTRYPOINT ["java","-Djava.security.egd=file:/dev/./urandom","-jar","./app.jar"]
